// <auto-generated />
using System;
using AquaPass;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaPass.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905093149_AddStaffUsers")]
    partial class AddStaffUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaPass.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AquaPass.Models.Sunbed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Sunbeds");
                });

            modelBuilder.Entity("AquaPass.Models.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            DayType = "Weekend",
                            Name = "Дорослий вхідний квиток(Вихідний)",
                            Price = 750.00m,
                            ServiceType = "EntranceTicketAdult",
                            ZoneId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            DayType = "Weekend",
                            Name = "Дитячий вхідний квиток(Вихідний)",
                            Price = 400.00m,
                            ServiceType = "EntranceTicketChild",
                            ZoneId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            DayType = "Weekday",
                            Name = "Дорослий вхідний квиток(Будний)",
                            Price = 550.00m,
                            ServiceType = "EntranceTicketAdult",
                            ZoneId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            DayType = "Weekday",
                            Name = "Дитячий вхідний квиток(Будний)",
                            Price = 350.00m,
                            ServiceType = "EntranceTicketChild",
                            ZoneId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            DayType = "Weekday",
                            Name = "Бунгало(Будний)",
                            Price = 600.00m,
                            ServiceType = "Bungalow",
                            ZoneId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            DayType = "Weekend",
                            Name = "Бунгало(Вихідний)",
                            Price = 800.00m,
                            ServiceType = "Bungalow",
                            ZoneId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            DayType = "Weekend",
                            Name = "Лежак(Вихідний)",
                            Price = 200.00m,
                            ServiceType = "Sunbed",
                            ZoneId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            DayType = "Weekday",
                            Name = "Лежак(Будний)",
                            Price = 150.00m,
                            ServiceType = "Sunbed",
                            ZoneId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("AquaPass.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EntrancePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("EntranceTariffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SunbedId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SunbedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntranceTariffId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SunbedId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("AquaPass.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AquaPass.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "VIP-зона"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Стандартна зона"
                        });
                });

            modelBuilder.Entity("AquaPass.Models.Sunbed", b =>
                {
                    b.HasOne("AquaPass.Models.Zone", null)
                        .WithMany("Sunbeds")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AquaPass.Models.Tariff", b =>
                {
                    b.HasOne("AquaPass.Models.Zone", "Zone")
                        .WithMany("Tariffs")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("AquaPass.Models.Ticket", b =>
                {
                    b.HasOne("AquaPass.Models.Tariff", "EntranceTariff")
                        .WithMany()
                        .HasForeignKey("EntranceTariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquaPass.Models.Order", "Order")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquaPass.Models.Sunbed", "Sunbed")
                        .WithMany()
                        .HasForeignKey("SunbedId");

                    b.Navigation("EntranceTariff");

                    b.Navigation("Order");

                    b.Navigation("Sunbed");
                });

            modelBuilder.Entity("AquaPass.Models.Order", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AquaPass.Models.Zone", b =>
                {
                    b.Navigation("Sunbeds");

                    b.Navigation("Tariffs");
                });
#pragma warning restore 612, 618
        }
    }
}
